
# syntax=docker/dockerfile:1
ARG REPO_URL=https://github.com/CICD-PROJECT-S103/k8sansimblebe.git

FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
ARG REPO_URL
WORKDIR /src
RUN apk add --no-cache git
RUN git clone "$REPO_URL" app
WORKDIR /src/app
RUN mvn -B -DskipTests clean package

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /src/app/target/*SNAPSHOT.jar app.jar
EXPOSE 8058
ENTRYPOINT ["java","-jar","/app/app.jar"]

