
# syntax=docker/dockerfile:1
ARG REPO_URL=https://github.com/CICD-PROJECT-S103/k8sansimblefe.git

FROM node:20-alpine AS build
ARG REPO_URL
WORKDIR /app
RUN apk add --no-cache git
RUN git clone "$REPO_URL" source
WORKDIR /app/source
RUN npm ci
RUN npm run build

FROM node:20-alpine AS runner
ENV NODE_ENV=production
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/source/out ./out
EXPOSE 3000
CMD ["serve", "-s", "out", "-l", "3000"]

