name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: portfolio_FE/package-lock.json
        
    - name: Install dependencies
      working-directory: ./portfolio_FE
      run: npm ci
      
    - name: Run tests
      working-directory: ./portfolio_FE
      run: npm test -- --coverage --watchAll=false
      
    - name: Build project
      working-directory: ./portfolio_FE
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${{ matrix.node-version }}
        path: portfolio_FE/build/